// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMEzlG6M5bg7IpZMI7LEMB9iV4rdWe44U',
    appId: '1:437349211477:android:a8f40ba8fdc22bff44a3dc',
    messagingSenderId: '437349211477',
    projectId: 'manga-s-verse',
    storageBucket: 'manga-s-verse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiwRyd-9vbB5ChT4Benlo53SwhHMj-MOQ',
    appId: '1:437349211477:ios:e62a478509d689c644a3dc',
    messagingSenderId: '437349211477',
    projectId: 'manga-s-verse',
    storageBucket: 'manga-s-verse.appspot.com',
    iosClientId: '437349211477-djr87ctrgjipdui1qsbptv3sq4u36m12.apps.googleusercontent.com',
    iosBundleId: 'com.example.publisherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiwRyd-9vbB5ChT4Benlo53SwhHMj-MOQ',
    appId: '1:437349211477:ios:98085d742bb39fbb44a3dc',
    messagingSenderId: '437349211477',
    projectId: 'manga-s-verse',
    storageBucket: 'manga-s-verse.appspot.com',
    iosClientId: '437349211477-btq5pl8srjvbc7rm65obd6jrk1qu18v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.publisherApp.RunnerTests',
  );
}
