// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvrBD1C6WOfoItEM8GX9xf9VrqBqjHLAw',
    appId: '1:437349211477:web:9f140bf43a02bf5a44a3dc',
    messagingSenderId: '437349211477',
    projectId: 'manga-s-verse',
    authDomain: 'manga-s-verse.firebaseapp.com',
    storageBucket: 'manga-s-verse.appspot.com',
    measurementId: 'G-9MVFF9FTFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMEzlG6M5bg7IpZMI7LEMB9iV4rdWe44U',
    appId: '1:437349211477:android:cc0fc82521a30e9444a3dc',
    messagingSenderId: '437349211477',
    projectId: 'manga-s-verse',
    storageBucket: 'manga-s-verse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiwRyd-9vbB5ChT4Benlo53SwhHMj-MOQ',
    appId: '1:437349211477:ios:226dedc69d6d106944a3dc',
    messagingSenderId: '437349211477',
    projectId: 'manga-s-verse',
    storageBucket: 'manga-s-verse.appspot.com',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiwRyd-9vbB5ChT4Benlo53SwhHMj-MOQ',
    appId: '1:437349211477:ios:c40657cecfaa086e44a3dc',
    messagingSenderId: '437349211477',
    projectId: 'manga-s-verse',
    storageBucket: 'manga-s-verse.appspot.com',
    iosBundleId: 'com.example.adminApp.RunnerTests',
  );
}
